apiVersion: v1
kind: Service
metadata:
  name: node-app-service               # Name of the service
spec:
  selector:
    app: node-app                      # Selector to match the Pods managed by this service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30000  # Port to access the service externally
  type: NodePort                  # Expose the service externally (use ClusterIP for internal-only)
